# GET http://localhost:3000/students/3

GET http://localhost:3000/grades/1

# POST http://localhost:3000/
# Content-Type: application/json

# {
#     "id": 4,
#     "name": [
#         "Emily",
#         "Hosoya"
#     ],
#     "grades": {
#         "English": "B",
#         "French": "B"
#     },
#     "username": "ehosoya",
#     "email": "ehosoya@gschool.com"
# }